{
  "FreeCAD": [
    "App",
    "Gui"
  ],
  "App": [
    "ActiveDocument",
    "addObject"
  ],
  "Gui": [
    "ActiveDocument",
    "ActiveView",
    "fitAll"
  ],
  "FreeCAD.ActiveDocument": [
    "addObject",
    "recompute"
  ],
  "App.ActiveDocument": [
    "addObject",
    "recompute"
  ],
  "Gui.ActiveDocument": [
    "fitAll"
  ],
  "FreeCAD.newDocument": [
    "newDocument"
  ],
  "Part": [
    "BoundBox",
    "Edges",
    "makeCylinder",
    "makeFillet",
    "makeVector",
    "Proxy",
    "cut",
    "fuse",
    "translate",
    "rotate"
  ],
  "Part.BoundBox": [
    "XLength",
    "YLength",
    "ZMax",
    "ZMin"
  ],
  "Part.Edges": [
    "Vertexes"
  ],
  "Part.makeCylinder": [
    "makeCylinder"
  ],
  "Part.makeFillet": [
    "makeFillet"
  ],
  "Part.makeVector": [
    "makeVector"
  ],
  "Part.Proxy": [
    "Proxy=0"
  ],
  "Part.cut": [
    "cut"
  ],
  "Part.fuse": [
    "fuse"
  ],
  "Part.translate": [
    "translate"
  ],
  "Part.rotate": [
    "rotate"
  ]
}