{
  "sys": [
    "sys.argv"
  ],
  "math": [
    "math.cos",
    "math.sin",
    "math.pi"
  ],
  "array": [
    "array.array"
  ],
  "random": [
    "random.randint"
  ],
  "os.path": [
    "os.path.abspath"
  ],
  "win32com.client": [
    "win32com.client.Dispatch"
  ],
  "CATIA.Application": [
    "CATIA.Application"
  ],
  "Part": [
    "Part.MainBody",
    "Part.OriginElements.PlaneXY",
    "Part.Shapefactory.AddNewPad"
  ],
  "Selection": [
    "Selection.VisProperties",
    "Selection.Add",
    "Selection.Clear",
    "Selection.Item2"
  ],
  "HybridBodies": [
    "HybridBodies.Add"
  ],
  "HybridShapeFactory": [
    "HybridShapeFactory.AddNewDirectionByCoord"
  ],
  "Product": [
    "Product.Products",
    "Product.AddComponentsFromFiles"
  ],
  "MovableObject": [
    "MovableObject.Apply"
  ]
}